"""
Generate a hand-crafted validation transcript that builds a realistic Unix
filesystem from scratch. This is holdout data — never used for training.

The session methodically creates /etc, /home, /usr, /var, /tmp, populates
them with realistic files, navigates around, reads files, and exercises
every command across the full range of the filesystem.

Target: 300+ carefully ordered commands.
"""

from tokenizer import BashTokenizer


def build_validation_transcript() -> str:
    """Return a single hand-crafted TTY transcript."""
    lines = []

    def cmd(c: str, output: str | None = None, err: bool = False):
        part = f"<prompt>{c}<eoi>"
        if err:
            part += "<err><eor>"
        elif output is not None:
            part += f"<output>{output}<eor>"
        else:
            part += "<output><eor>"
        lines.append(part)

    # --- Start at empty root ---
    cmd("pwd", "/")
    cmd("ls")

    # === Build /etc ===
    cmd("mkdir etc")
    cmd("cd etc")
    cmd("pwd", "/etc")
    cmd("mkdir ssh")
    cmd("mkdir ssl")
    cmd("mkdir network")
    cmd("mkdir default")
    cmd("mkdir cron.d")
    cmd("mkdir pam.d")
    cmd("echo root:0:0:root:/root:/bin/sh > passwd")
    cmd("echo daemon:1:1:daemon:/usr/sbin:/bin/sh >> passwd")
    # Actually we only have > so let's just use echo >
    cmd("echo 127.0.0.1 localhost > hosts")
    cmd("echo nameserver 8.8.8.8 > resolv.conf")
    cmd("echo myhost > hostname")
    cmd("touch fstab")
    cmd("touch mtab")
    cmd("echo alias0 eth0 > modprobe.conf")
    cmd("ls", "cron.d  default  fstab  hostname  hosts  modprobe.conf  mtab  network  pam.d  passwd  resolv.conf  ssh  ssl")
    cmd("cd ssh")
    cmd("touch sshd_config")
    cmd("echo port 22 > sshd_config")
    cmd("touch ssh_config")
    cmd("echo host all > ssh_config")
    cmd("ls", "ssh_config  sshd_config")
    cmd("cat sshd_config", "port 22")
    cmd("cd ..")
    cmd("cd ssl")
    cmd("mkdir certs")
    cmd("mkdir private")
    cmd("touch openssl.cnf")
    cmd("cd certs")
    cmd("touch ca.pem")
    cmd("touch server.pem")
    cmd("ls", "ca.pem  server.pem")
    cmd("cd /")
    cmd("pwd", "/")

    # === Build /home with two users ===
    cmd("mkdir home")
    cmd("cd home")
    cmd("mkdir alice")
    cmd("mkdir bob")
    cmd("cd alice")
    cmd("pwd", "/home/alice")
    cmd("mkdir desktop")
    cmd("mkdir documents")
    cmd("mkdir downloads")
    cmd("mkdir pictures")
    cmd("mkdir projects")
    cmd("touch .bashrc")
    cmd("echo path /usr/bin:/bin > .bashrc")
    cmd("touch .profile")
    cmd("echo alias ls ls -la > .profile")
    cmd("cd documents")
    cmd("echo meeting notes from monday > notes.txt")
    cmd("echo todo fix the build > todo.txt")
    cmd("echo todo update docs >> todo.txt")
    cmd("echo todo run tests >> todo.txt")
    cmd("echo shopping list eggs milk bread > list.txt")
    cmd("ls", "list.txt  notes.txt  todo.txt")
    cmd("cat notes.txt", "meeting notes from monday")
    cmd("cat todo.txt", "todo fix the build\ntodo update docs\ntodo run tests")
    cmd("cd ..")
    cmd("cd downloads")
    cmd("touch report.pdf")
    cmd("touch data.csv")
    cmd("touch backup.tar")
    cmd("ls", "backup.tar  data.csv  report.pdf")
    cmd("cd ..")
    cmd("cd projects")
    cmd("mkdir webapp")
    cmd("cd webapp")
    cmd("mkdir src")
    cmd("mkdir tests")
    cmd("mkdir docs")
    cmd("mkdir config")
    cmd("echo print hello world > src/main.py")
    cmd("echo import main > src/init.py")
    cmd("echo assert true > tests/test.py")
    cmd("echo name webapp version 1 > config/app.cfg")
    cmd("touch readme.md")
    cmd("echo webapp readme > readme.md")
    cmd("touch .gitignore")
    cmd("echo build dist .env > .gitignore")
    cmd("ls", ".gitignore  config  docs  readme.md  src  tests")
    cmd("cat readme.md", "webapp readme")
    cmd("cat .gitignore", "build dist .env")
    cmd("cd src")
    cmd("ls", "init.py  main.py")
    cmd("cat main.py", "print hello world")
    cmd("cd /home/alice")
    cmd("cd pictures")
    cmd("touch photo01.jpg")
    cmd("touch photo02.jpg")
    cmd("touch sunset.png")
    cmd("ls", "photo01.jpg  photo02.jpg  sunset.png")
    cmd("cd /home/bob")
    cmd("pwd", "/home/bob")
    cmd("mkdir desktop")
    cmd("mkdir documents")
    cmd("mkdir downloads")
    cmd("mkdir music")
    cmd("mkdir scripts")
    cmd("touch .bashrc")
    cmd("echo export editor vim > .bashrc")
    cmd("touch .vimrc")
    cmd("echo set number > .vimrc")
    cmd("cd scripts")
    cmd("echo echo backup started > backup.sh")
    cmd("echo echo deploy done > deploy.sh")
    cmd("echo echo cleanup finished > clean.sh")
    cmd("ls", "backup.sh  clean.sh  deploy.sh")
    cmd("cat backup.sh", "echo backup started")
    cmd("cd ..")
    cmd("cd documents")
    cmd("echo quarterly report draft > report.txt")
    cmd("echo budget 2025 draft > budget.txt")
    cmd("ls", "budget.txt  report.txt")
    cmd("cat report.txt", "quarterly report draft")
    cmd("cd /")

    # === Build /usr ===
    cmd("mkdir usr")
    cmd("cd usr")
    cmd("mkdir bin")
    cmd("mkdir lib")
    cmd("mkdir share")
    cmd("mkdir local")
    cmd("mkdir include")
    cmd("cd bin")
    cmd("touch sh")
    cmd("touch ls")
    cmd("touch cat")
    cmd("touch grep")
    cmd("touch find")
    cmd("touch sort")
    cmd("touch head")
    cmd("touch tail")
    cmd("touch sed")
    cmd("touch awk")
    cmd("touch cp")
    cmd("touch mv")
    cmd("touch rm")
    cmd("touch chmod")
    cmd("touch chown")
    cmd("touch tar")
    cmd("touch gzip")
    cmd("ls", "awk  cat  chmod  chown  cp  find  grep  gzip  head  ls  mv  rm  sed  sh  sort  tail  tar")
    cmd("cd ..")
    cmd("cd lib")
    cmd("touch libc.so")
    cmd("touch libm.so")
    cmd("touch libdl.so")
    cmd("touch librt.so")
    cmd("ls", "libc.so  libdl.so  libm.so  librt.so")
    cmd("cd ..")
    cmd("cd share")
    cmd("mkdir man")
    cmd("mkdir doc")
    cmd("mkdir locale")
    cmd("cd man")
    cmd("mkdir man1")
    cmd("mkdir man5")
    cmd("mkdir man8")
    cmd("cd man1")
    cmd("touch ls.1")
    cmd("touch grep.1")
    cmd("touch find.1")
    cmd("cd /usr/local")
    cmd("mkdir bin")
    cmd("mkdir lib")
    cmd("mkdir share")
    cmd("cd bin")
    cmd("touch node")
    cmd("touch python3")
    cmd("touch pip")
    cmd("ls", "node  pip  python3")
    cmd("cd /")

    # === Build /var ===
    cmd("mkdir var")
    cmd("cd var")
    cmd("mkdir log")
    cmd("mkdir cache")
    cmd("mkdir spool")
    cmd("mkdir mail")
    cmd("mkdir tmp")
    cmd("mkdir run")
    cmd("cd log")
    cmd("echo jan 01 system started > syslog")
    cmd("echo jan 01 sshd restarted >> syslog")
    cmd("echo jan 02 cron fired >> syslog")
    cmd("echo jan 01 login alice > auth.log")
    cmd("echo jan 01 login bob >> auth.log")
    cmd("echo 200 get /index.html > access.log")
    cmd("echo 200 get /style.css >> access.log")
    cmd("echo 304 get /logo.png >> access.log")
    cmd("echo 500 post /api/data > error.log")
    cmd("touch daemon.log")
    cmd("touch kern.log")
    cmd("touch debug.log")
    cmd("ls", "access.log  auth.log  daemon.log  debug.log  error.log  kern.log  syslog")
    cmd("cat syslog", "jan 01 system started\njan 01 sshd restarted\njan 02 cron fired")
    cmd("cat access.log", "200 get /index.html\n200 get /style.css\n304 get /logo.png")
    cmd("cat error.log", "500 post /api/data")
    cmd("cd ..")
    cmd("cd cache")
    cmd("mkdir apt")
    cmd("mkdir pip")
    cmd("cd apt")
    cmd("touch pkgcache.bin")
    cmd("touch srcpkgcache.bin")
    cmd("cd /var/spool")
    cmd("mkdir cron")
    cmd("mkdir mail")
    cmd("cd cron")
    cmd("touch crontab")
    cmd("echo 0 5 daily /bin/backup > crontab")
    cmd("cd /var/mail")
    cmd("touch alice")
    cmd("touch bob")
    cmd("echo you have new mail > alice")
    cmd("cat alice", "you have new mail")
    cmd("cd /var/run")
    cmd("touch sshd.pid")
    cmd("touch crond.pid")
    cmd("echo 1024 > sshd.pid")
    cmd("echo 1025 > crond.pid")
    cmd("ls", "crond.pid  sshd.pid")
    cmd("cd /")

    # === Build /tmp ===
    cmd("mkdir tmp")
    cmd("cd tmp")
    cmd("touch sess_a1b2c3")
    cmd("touch sess_d4e5f6")
    cmd("touch lock.pid")
    cmd("echo 9981 > lock.pid")
    cmd("mkdir scratch")
    cmd("cd scratch")
    cmd("echo temporary working data > work.dat")
    cmd("echo partial result set > partial.out")
    cmd("ls", "partial.out  work.dat")
    cmd("cat work.dat", "temporary working data")
    cmd("cd /")

    # === Build /srv ===
    cmd("mkdir srv")
    cmd("cd srv")
    cmd("mkdir www")
    cmd("cd www")
    cmd("mkdir blog")
    cmd("mkdir api")
    cmd("cd blog")
    cmd("mkdir posts")
    cmd("mkdir drafts")
    cmd("mkdir static")
    cmd("cd posts")
    cmd("echo hello world this is my first post > hello-world.md")
    cmd("echo tips for linux admin > linux-tips.md")
    cmd("echo how to set up ssh keys > ssh-setup.md")
    cmd("echo debugging with strace > debug-tools.md")
    cmd("echo bash scripting basics > bash-intro.md")
    cmd("ls", "bash-intro.md  debug-tools.md  hello-world.md  linux-tips.md  ssh-setup.md")
    cmd("cat hello-world.md", "hello world this is my first post")
    cmd("cat bash-intro.md", "bash scripting basics")
    cmd("cd ..")
    cmd("cd drafts")
    cmd("echo work in progress networking > draft-network.md")
    cmd("echo work in progress containers > draft-docker.md")
    cmd("ls", "draft-docker.md  draft-network.md")
    cmd("cd ..")
    cmd("cd static")
    cmd("touch style.css")
    cmd("touch main.js")
    cmd("touch logo.svg")
    cmd("touch favicon.ico")
    cmd("ls", "favicon.ico  logo.svg  main.js  style.css")
    cmd("cd /srv/www/api")
    cmd("echo from app import create > server.py")
    cmd("echo routes config > routes.cfg")
    cmd("echo db host localhost port 5432 > db.conf")
    cmd("ls", "db.conf  routes.cfg  server.py")
    cmd("cat db.conf", "db host localhost port 5432")
    cmd("cd /")

    # === Build /opt ===
    cmd("mkdir opt")
    cmd("cd opt")
    cmd("mkdir tools")
    cmd("cd tools")
    cmd("mkdir monitoring")
    cmd("mkdir backup")
    cmd("cd monitoring")
    cmd("echo check host interval 60 > check.cfg")
    cmd("echo alert email admin > alert.cfg")
    cmd("touch monitor.sh")
    cmd("echo run checks > monitor.sh")
    cmd("cd ..")
    cmd("cd backup")
    cmd("echo target /var/backup > config.cfg")
    cmd("echo schedule daily 0300 > schedule.cfg")
    cmd("touch run_backup.sh")
    cmd("ls", "config.cfg  run_backup.sh  schedule.cfg")
    cmd("cd /")

    # === Error cases (intentional) ===
    cmd("cd nonexistent", err=True)
    cmd("cat no_such_file.txt", err=True)
    cmd("mkdir etc", err=True)  # already exists
    cmd("rm phantom.log", err=True)
    cmd("cd ..", err=True)  # already at root
    cmd("cat /var/log/missing.log", err=True)
    cmd("mkdir home", err=True)

    # === Navigation stress test — jump around and verify ===
    cmd("cd /home/alice/projects/webapp/src")
    cmd("pwd", "/home/alice/projects/webapp/src")
    cmd("ls", "init.py  main.py")
    cmd("cat main.py", "print hello world")
    cmd("cd /var/log")
    cmd("pwd", "/var/log")
    cmd("cat auth.log", "jan 01 login alice\njan 01 login bob")
    cmd("cd /srv/www/blog/posts")
    cmd("pwd", "/srv/www/blog/posts")
    cmd("cat ssh-setup.md", "how to set up ssh keys")
    cmd("cd /etc/ssh")
    cmd("cat sshd_config", "port 22")
    cmd("cd /home/bob/scripts")
    cmd("cat deploy.sh", "echo deploy done")
    cmd("cd /usr/local/bin")
    cmd("ls", "node  pip  python3")
    cmd("cd /tmp/scratch")
    cmd("cat partial.out", "partial result set")
    cmd("cd /var/mail")
    cmd("cat bob")
    cmd("cd /opt/tools/monitoring")
    cmd("cat check.cfg", "check host interval 60")
    cmd("cd /")
    cmd("pwd", "/")

    # === Final ls at various levels ===
    cmd("ls", "etc  home  opt  srv  tmp  usr  var")
    cmd("cd etc")
    cmd("ls", "cron.d  default  fstab  hostname  hosts  modprobe.conf  mtab  network  pam.d  passwd  resolv.conf  ssh  ssl")
    cmd("cd /home")
    cmd("ls", "alice  bob")
    cmd("cd /usr")
    cmd("ls", "bin  include  lib  local  share")
    cmd("cd /var")
    cmd("ls", "cache  log  mail  run  spool  tmp")
    cmd("cd /")

    # === More file creation and reading to push past 300 ===
    cmd("cd /home/alice/documents")
    cmd("echo meeting agenda for tuesday > agenda.txt")
    cmd("echo action items from standup > actions.txt")
    cmd("echo project timeline q2 > timeline.txt")
    cmd("ls", "actions.txt  agenda.txt  list.txt  notes.txt  timeline.txt  todo.txt")
    cmd("cat actions.txt", "action items from standup")
    cmd("cd /home/bob/documents")
    cmd("echo server migration plan > migration.txt")
    cmd("echo dns changes needed > dns.txt")
    cmd("echo firewall rules update > firewall.txt")
    cmd("ls", "budget.txt  dns.txt  firewall.txt  migration.txt  report.txt")
    cmd("cat migration.txt", "server migration plan")

    cmd("cd /home/bob/music")
    cmd("touch track01.mp3")
    cmd("touch track02.mp3")
    cmd("touch track03.mp3")
    cmd("touch playlist.m3u")
    cmd("echo track01 track02 track03 > playlist.m3u")
    cmd("ls", "playlist.m3u  track01.mp3  track02.mp3  track03.mp3")
    cmd("cat playlist.m3u", "track01 track02 track03")

    cmd("cd /srv/www/blog/posts")
    cmd("echo setting up monitoring with scripts > monitoring.md")
    cmd("echo log rotation best practices > logrotate.md")
    cmd("echo cron job patterns > cron-tips.md")
    cmd("ls", "bash-intro.md  cron-tips.md  debug-tools.md  hello-world.md  linux-tips.md  logrotate.md  monitoring.md  ssh-setup.md")

    cmd("cd /var/log")
    cmd("echo jan 02 service restarted > daemon.log")
    cmd("echo jan 02 kernel module loaded > kern.log")
    cmd("cat daemon.log", "jan 02 service restarted")
    cmd("cat kern.log", "jan 02 kernel module loaded")

    # Final jump back
    cmd("cd /")
    cmd("pwd", "/")
    cmd("ls", "etc  home  opt  srv  tmp  usr  var")

    transcript = "".join(lines) + "<eos>"
    return transcript


def main():
    transcript = build_validation_transcript()
    tok = BashTokenizer()

    # Validate
    try:
        ids = tok.encode(transcript)
        decoded = tok.decode(ids)
        roundtrip = decoded == transcript
    except ValueError as e:
        print(f"TOKENIZATION FAILED: {e}")
        # Find the bad spot
        for i, ch in enumerate(transcript):
            if ch not in "abcdefghijklmnopqrstuvwxyz0123456789/._ ->\"\n@:#" and not transcript[i:].startswith("<prompt>") and not transcript[i:].startswith("<output>") and not transcript[i:].startswith("<err>") and not transcript[i:].startswith("<pad>") and not transcript[i:].startswith("<eos>"):
                print(f"  Bad char {ch!r} at pos {i}: ...{transcript[max(0,i-20):i+20]}...")
                break
        return

    num_cmds = transcript.count("<prompt>")
    print(f"Commands: {num_cmds}")
    print(f"Tokens: {len(ids)}")
    print(f"Round-trip OK: {roundtrip}")
    print()
    print("First 2000 chars:")
    print(transcript[:2000])
    print(f"\n--- ({len(transcript)} total chars) ---")

    # Write to file
    import json, os
    os.makedirs("data", exist_ok=True)
    with open("data/validation.jsonl", "w") as f:
        record = {
            "transcript": transcript,
            "num_tokens": len(ids),
            "num_exchanges": num_cmds,
            "type": "validation",
        }
        f.write(json.dumps(record) + "\n")
    print(f"\nWritten to data/validation.jsonl")


if __name__ == "__main__":
    main()
